import"./assets/top-link-CI3MJDcL.js";import{a as v}from"./assets/vendor-C0Nsn3Ff.js";const y="https://api.themoviedb.org/3",f="/movie/top_rated",L="/search/movie",b="5cd3b967f25ca5ea88c6b3955d7951c5",h=document.querySelector(".moviesContainer"),o=document.getElementById("top-load-btn"),w=document.querySelector(".top-form"),n=document.querySelector(".loader-container"),r=document.querySelector(".error"),c=document.querySelector(".modal"),E=document.querySelector(".modal-close-btn"),S=document.querySelector(".modal-info");let i=1,d="";async function m(e="",t=1){const s=e?L:f;try{n.style.display="block";const{data:a}=await v(`${y}${s}`,{params:{api_key:b,query:e,page:t}});return o.classList.replace("load-more-hidden","btn"),a.results}catch(a){return console.log(a.message),r.classList.replace("error-hidden","error-message"),[]}finally{n.style.display="none"}}(async function(){try{const t=await m();p(t)}catch(t){console.log(t.message),r.classList.replace("error-hidden","error-message")}})();function M(e){return e.map(({poster_path:t,title:s})=>`<li class="movies-list-item">
          <img src="https://image.tmdb.org/t/p/w200${t}" alt="${s}" class="movies-item-img" width="234" height="351">
          <h3 class="movies-item-title">${s}</h3>
      </li>`).join("")}function p(e){if(!e||e.length===0){r.classList.replace("error-hidden","error-message");return}r.classList.replace("error-message","error-hidden");const t=M(e);h.insertAdjacentHTML("beforeend",t),document.querySelectorAll(".movies-list-item").forEach((a,l)=>{a.addEventListener("click",()=>T(e[l]))})}o.addEventListener("click",$);w.addEventListener("submit",q);E.addEventListener("click",u);async function $(){o.classList.replace("btn","load-more-hidden"),o.disabled=!0,i+=1;try{const e=await m(d,i);p(e);const t=document.querySelector(".movies-list-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({left:0,top:s,behavior:"smooth"})}}catch(e){console.log(e.message),r.classList.replace("error-hidden","error-message")}finally{o.classList.replace("load-more-hidden","btn"),o.disabled=!1}}async function q(e){e.preventDefault();const t=e.currentTarget.elements.search.value.trim();t!==d&&(d=t,i=1,h.innerHTML=""),n.classList.remove("hidden"),o.classList.replace("btn","load-more-hidden");try{const s=await m(t,i);p(s),s.length>0&&o.classList.replace("load-more-hidden","btn")}catch(s){console.log(s.message),r.classList.replace("error-hidden","error-message")}finally{n.classList.add("hidden"),e.target.elements.search.value=""}}function T(e){const{title:t,overview:s,poster_path:a,release_date:l,vote_average:g}=e;S.innerHTML=`
    <img src="https://image.tmdb.org/t/p/w500${a}" alt="${t}" width="300" class="modal-img">
    <div class="modal-wrap">
    <h2 class="modal-title">${t}</h2>
    <p class="modal-text">Release Date: <span class="modal-text-span">${l}</span></p>
    <p class="modal-text">Rating: <span class="modal-text-span">${g}</span></p>
    <p class="modal-text">Overview: <span class="modal-text-span">${s}</span></p>
    </div>
  `,c.classList.remove("hidden")}function u(){c.classList.add("hidden")}c.addEventListener("click",e=>{e.target===c&&u()});
//# sourceMappingURL=page-3.js.map
